# not actually in active use.  Saved so should I need it on a remote system, I have it.

# reset ^b to use ^q
unbind C-b
set -g prefix C-q

# ^q^q will flip back to previous window
bind C-q last-window

# increase scrollback buffer
set-option -g history-limit 100000

# ^qy will toggle pane sync (send typing to all windows or not)
bind y set-window-option synchronize-panes \; display "sync #{?pane_synchronized,ON,OFF}"

# bind dash to split windows vertically, pipe ('|') to split horizontally
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
# cover the "missed-shift-key" case for horizontal
bind \\ split-window -h -c "#{pane_current_path}"

#Set status bar on bottom
set -g status-left '#S '
set -g status-right '(#I:#P) #{=22:pane_title} %H:%M %d-%b-%y'

#radically reduce esc delay to make vim feel better
set -sg escape-time 0

## play with these if tmux becomes needed locally again (looking at you gastown)
#focus follows mouse akin to ghostty/others. Not sure I like this on remote box tmux...
# set -g mouse on

# use 1-indexing for windows
# set -g base-index 1
# setw -g pane-base-index 1
# set -g renumber-windows on

# vim cmds for copy mode
# setw -g mode-keys vi

# fix colors
# set -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",*256col*:Tc"

## reload config
# bind r source-file ~/.tmux.conf \; display "reloaded"
